version: "3.9"

services:
  cache-service-app:
    image: public.ecr.aws/y7v2w8b2/redstone-cache-service:latest
    depends_on:
      - mongodb
    environment:
      MONGO_DB_URL: "mongodb://mongodb:27017"
      ENABLE_STREAMR_LISTENING: true
      ENABLE_DIRECT_POSTING_ROUTES: false
      MOCK_DATA_SERVICE_ID_FOR_PACKAGES: false

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - db-volume:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:27017"

volumes:
  db-volume:
